export const ActionTypes = {
    GET_NUMBER_CART:'GET_NUMBER_CART',
    ADD_CART: 'ADD_CART',
    INCREASE_QUANTITY: 'INCREASE_QUANTITY',
    DECRESE_QUANTITY: 'DECRESE_QUANTITY',
    DELETE_CART: 'DELETE_CART'
}